using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;

namespace TemplateLoader.Model
{
    class TemplateLoaderDbInitializer : DropCreateDatabaseAlways<TemplateLoaderDbContext>
    {
        protected override void Seed(TemplateLoaderDbContext context)
        {
            #region customers

            List<Customer> customers = new List<Customer>
            {
                new Customer() {CustomerName="Ameriprise"} ,
                new Customer() {CustomerName="Citrix"} ,
                new Customer() {CustomerName="AT&T"} ,
                new Customer() {CustomerName="Carlyle"} ,
                new Customer() {CustomerName="Newcrest Mining"} ,
                new Customer() {CustomerName="Cooperators"} ,
                new Customer() {CustomerName="Dansk Supermarked Gruppen (DSG)"} ,
                new Customer() {CustomerName="Topdenmark"} ,
                new Customer() {CustomerName="Itella"} ,
                new Customer() {CustomerName="Airbus"} ,
                new Customer() {CustomerName="Boursorama"} ,
                new Customer() {CustomerName="CEGID"} ,
                new Customer() {CustomerName="Comafranc"} ,
                new Customer() {CustomerName="Dior"} ,
                new Customer() {CustomerName="Socotec"} ,
                new Customer() {CustomerName="Solon"} ,
                new Customer() {CustomerName="Veolia"} ,
                new Customer() {CustomerName="VSCT"} ,
                new Customer() {CustomerName="Ernst & Young"} ,
                new Customer() {CustomerName="ICR"} ,
                new Customer() {CustomerName="INTERCOS"} ,
                new Customer() {CustomerName="MEMBRANE"} ,
                new Customer() {CustomerName="Kyocera"} ,
                new Customer() {CustomerName="RTL Nederland"} ,
                new Customer() {CustomerName="Hof Hoorneman Bankiers NV"} ,
                new Customer() {CustomerName="Williams & Glyn (W&G)"} ,
                new Customer() {CustomerName="Carphone Warehouse"} ,
                new Customer() {CustomerName="Unipart"} ,
                new Customer() {CustomerName="Mead Johnson"} ,
                new Customer() {CustomerName="Direct Energy Marketing Ltd"} ,
                new Customer() {CustomerName="Golden Nugget"} ,
                new Customer() {CustomerName="Golden Nugget Atlantic"} ,
                new Customer() {CustomerName="Landry"} ,
                new Customer() {CustomerName="NYK Business Systems Americas, Inc. (NBSA)"} ,
                new Customer() {CustomerName="Welch Allyn"} ,
                new Customer() {CustomerName="SONY DADC US INC"} ,
                new Customer() {CustomerName="Stryker"} ,
                new Customer() {CustomerName="LOREAL USA INC"} ,
                new Customer() {CustomerName="Neovia"} ,
                new Customer() {CustomerName="Pearson"} ,
                new Customer() {CustomerName="ANA G MENDEZ SISTEMA UNIVERSITARIO INCOR"} ,
                new Customer() {CustomerName="IGS Itau Unibanco"} ,
                new Customer() {CustomerName="Oncor/Smart Meter Texas"} ,
                new Customer() {CustomerName="Panasonic"} ,
                new Customer() {CustomerName="Amalgamated"} ,
                new Customer() {CustomerName="Gardner Denver"} ,
                new Customer() {CustomerName="Aurora Health Care"} ,
                new Customer() {CustomerName="Goldman Sachs"} ,
                new Customer() {CustomerName="Plantronics"} ,
                new Customer() {CustomerName="Miller Coors"} ,
                new Customer() {CustomerName="Phillips"} ,
                new Customer() {CustomerName="Wire&Plastic Products"} ,
                new Customer() {CustomerName="Yara"}
            };

            foreach(var item in customers)
            {
                context.Customers.Add(item);
            }
            context.SaveChanges();
            #endregion

            //#region sites

            //List<Site> sites = new List<Site>
            //{
            //    new Site () { SiteName="AIRCOL01-IFR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ALILEO01-IUS-02-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ALISLM01-IUS-02-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ALISTF01-IUS-02-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ALIWPL01-IUS-02-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmbdr01-ius-01-001-nbmana", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="AFILEX01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="AFILEX01-IUS-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="AFILEX01-IUS-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="AFISTL01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="AFISTL01-IUS-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="amxmar01-ica-01-001-axss", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmstf01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmgfd01-iuk-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="BIUPOK01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="BIURTP01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmstf01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="BSRCOL01-IFR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARBDR01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARHKC01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARHKC02-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARLON01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARLUX01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARMIL01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARNYC01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARPAR01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARROS01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARRST01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARRST01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARSLO01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARSTR01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARTKY01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CARWDC01-CAR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWGFD01-IUK-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWGFD01-IUK-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-002-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-003-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-004-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-005-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-006-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-007-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-008-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-009-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CPWNHB01-IUK-01-010-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CCHALL01-ATT-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CCHALL01-ATT-01-002-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CCHMES01-ATT-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CCHMES01-ATT-01-002-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CGDCOL01-IFR-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CGDCOL01-IFR-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CGDCOL01-IFR-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmwrd01-inl-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CTXAMD01-INL-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CTXSIN01-ISG-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CTXMIA01-ADC-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CTXSTC01-ADC-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmcol01-ifr-02-001-axss", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmcol01-ifr-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CGLBRE01-ICA-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="CGLMAR01-ICA-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DSG_TSMB801", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DSG_TSMB803", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DSG_TSMP402", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DSG_TSMP404", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DSGBLP01-IDM-01-002-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DLHSLB01-IUS-01-001-TSSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DLHWST01-IUS-01-001-TSSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DIOCOL01-IFR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="HBKPMSFP", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="HBKPNDM1", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DEMRTP01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DEMMIS01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DEMSTF01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DEMASH01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="DOJRTP02-0001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ENYFRK01-IGE-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ENYEHN01-IGE-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="GDVSTF01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmbdr01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="lanalc01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmbdr01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="HRSGFD01-IUK-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmstf01-ius-01-001-axss", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmwrd01-inl-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ICRLOD01-IIT-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="IGMKSC01-0001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="IGMMES01-ATT-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="IGMPHX01-0001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="IGMRTP01-0001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="KOLHEL01-IFN-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="KOLHEL01-IFN-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="KOLHEL01-IFN-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="KOLHEL02-IFN-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="KOLHEL02-IFN-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="KOLHEL02-IFN-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmstf01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LANALC01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LANSTF01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LORSEC01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LORSEC01-IUS-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LNDWAR01-IUK-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LNDWAR01-IUK-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LNDWAR01-IUK-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LNDWAR01-IUK-04-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="WAGBIR01-IUK-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="WAGBIR01-IUK-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="WAGBIR01-IUK-04-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="WAGBIR01-IUK-05-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="LOWMAN01-VZN-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRALG01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCREDN01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRFTW01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRGLD01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRIRW01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRMWK01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRCLB01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRDAL01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRCLB01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRCLB01-IUS-01-002-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRCLB01-IUS-01-003-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRMWK02-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRSHE01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MCRTTN01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="MOBMLG01-MOB-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="NBSASEA01-0001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="NBSASEC01-0001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="NBSCLB01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="NEOBDR01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="NCMBHD01-IAU-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="nbsclb01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="rtlhvm01-inl-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="IBMALM01-INL-01-001-AXSS", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmsol01-ise-01-001-axms", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="sctcol01-ifr-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="IBMALM01-INL-01-001-AXSS ", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmcol01-ifr-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="STRDAL01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="STRLON02-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="STRLON02-IUS-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="STRTOK02-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="tfynyc01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="TDMEJB01-IDM-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="TDMEJB01-IDM-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="TDMEJB01-IDM-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="TDMEJB01-IDM-04-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="OUTCOL01-IFR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PANPOK01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PANPOK01-IUS-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PANPOK01-IUS-01-001-TSVE", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PSNPOK01-IUS-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PSNPOK01-IUS-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PSNPOK01-IUS-04-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PSNPOK01-IUS-05-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="pepstf01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PHLHRT01-PHL-02-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PHLMAR01-PHL-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PHLRTP01-PHL-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PHLRTP01-PHL-03-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PLTBDR01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PLTSCZ01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PDXNYC01-ATT-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="PDXSEC01-ATT-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="TFYNYC01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="TFYPSY01-IUS-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="ibmbdr01-ius-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="VEOCOL01-IFR-01-001-NBMA", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="vsccol01-ifr-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="WALROC01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="WALSTF01-IUS-01-001-TSM", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yaramb01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yargot01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yargua01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarprs01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarrav01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarrsk01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarsck01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarsck01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarslu01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yarter01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yartku01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //    new Site () { SiteName="yartpa01-yar-01-001-nbma", CustomerId=0, SiteOwnerId=0} ,
            //};

            //foreach(var item in sites)
            //{
            //    context.Sites.Add(item);
            //}
            //context.SaveChanges();

            //#endregion
            base.Seed(context);
        }
    }
}
